#!/bin/sh

# starship
curl -sS https://starship.rs/install.sh | sh

# fish plugin manager
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source

fisher install jorgebucaran/fisher
fisher install jethrokuan/z

if ! command -v stow &> /dev/null; then
    echo "stow is not installed"
    exit 1
fi
