#!/bin/bash

# starship
curl -sS https://starship.rs/install.sh | sh

# asdf-vm
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1

# antigen
curl -L git.io/antigen > $HOME/antigen.zsh

if ! command -v stow &> /dev/null; then
    echo "stow is not installed"
    exit 1
fi
